### PR TITLE
Update run.sh

### PR DESCRIPTION
**Pull request by Identity-Unkn0wn**
Need to update the script to the new link on the edge github page.

### CODE REVIEW

**Comment by dragonfire1119** [comment]
Why I keep it on the Github repo URL is in case `casaos-appstore.paodayag.dev` goes down again. It should be the same.

**Comment by Identity-Unkn0wn** [comment]
Just the page that casaOS links you to has the casaos-appstore.paodayag.dev link in there to add the store. Honestly just with the big bear repo had plex, then I wouldn't need the script.you can delete this. just thought I was being helpful.

**Comment by dragonfire1119** [comment]
I understand I'm not putting down the pull request; I just wanted information on why it needs to be changed. Also, I was letting you know it had gone down before. I do very much appreciate pull requests and the help.

You can suggest Plex to be added here: https://community.bigbeartechworld.com/c/big-bear-casaos/bigbearcasaos-suggestions/40

**Comment by dragonfire1119** [comment]
I'm going to close this. I think right now we should stick to the more stable GitHub URL. Feel free to create more PR's. I do appreciate you trying to help!

I also added Plex: https://community.bigbeartechworld.com/t/added-plex-to-bigbearcasaos/912?u=dragonfire1119

**Pull request closed without merging**
